"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.0.5.
https://docs.djangoproject.com/en/6.0/topics/settings/
"""

# IMPORTS
from datetime import timedelta
from pathlib import Path
import re

from decouple import config
import dj_database_url
from django.core.exceptions import ImproperlyConfigured

BASE_DIR = Path(__file__).resolve().parent.parent


# SEGURIDAD
SECRET_KEY = config('DJANGO_SECRET_KEY')
DEBUG = config('DJANGO_DEBUG', cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')

# Identidad corporativa de las cuentas operativas. La ausencia de la variable
# conserva un valor seguro para SassBlum; declararla vacía o con un dominio
# inválido detiene el arranque en lugar de desactivar silenciosamente la regla.
WORKER_EMAIL_DOMAIN = config(
    'WORKER_EMAIL_DOMAIN', default='sassblum.com'
).strip().lower()
_DOMAIN_PATTERN = re.compile(
    r'^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$',
    re.IGNORECASE,
)
if not WORKER_EMAIL_DOMAIN or not _DOMAIN_PATTERN.fullmatch(WORKER_EMAIL_DOMAIN):
    raise ImproperlyConfigured(
        'WORKER_EMAIL_DOMAIN debe contener un dominio corporativo válido y no vacío.'
    )


# APLICACIONES
INSTALLED_APPS = [
    'daphne',
    # Django defaults
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'channels',
    'anymail',
    # SassBlum apps
    'apps.authentication',
    'apps.catalog',
    'apps.clientes',
    'apps.gallery',
    'apps.testimonials',
    'apps.tickets',
    'apps.notifications',
    'apps.reports',
    'apps.realtime',
]


# MIDDLEWARE
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',          # Debe ir primero
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# CORS
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in config(
        'CORS_ALLOWED_ORIGINS', default='http://localhost:5173'
    ).split(',')
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in config('CSRF_TRUSTED_ORIGINS', default='').split(',')
    if origin.strip()
]

# CORS preflight cache — reduce OPTIONS requests
CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours

# WEBSOCKETS — orígenes permitidos en el handshake (ver config/asgi.py)
# El WS va DIRECTO a Render (el rewrite de Vercel NO proxea WebSockets), así que
# el Origin del handshake es el dominio del frontend, no el de la API. Con
# AllowedHostsOriginValidator (que valida contra ALLOWED_HOSTS) todo handshake
# desde Vercel se rechazaba antes de llegar al consumer.
# Solo se aceptan orígenes exactos controlados. Cada preview que necesite acceso
# debe añadirse explícitamente mediante CORS_ALLOWED_ORIGINS.
WS_ALLOWED_ORIGINS = [*CORS_ALLOWED_ORIGINS]

# URLS Y WSGI / ASGI
ROOT_URLCONF = 'config.urls'
WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'   # Requerido por Django Channels


# TEMPLATES
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# BASE DE DATOS — Supabase / PostgreSQL
DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL'),
        conn_max_age=config('CONN_MAX_AGE', default=0, cast=int),
    )
}


# MODELO DE USUARIO PERSONALIZADO
AUTH_USER_MODEL = 'authentication.User'


# VALIDACIÓN DE CONTRASEÑAS
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# DJANGO REST FRAMEWORK
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Rate limiting — OWASP A07:2021
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/minute',
        'user': '100/minute',
    },
    # Pagination — prevents huge responses
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}


# JWT — djangorestframework-simplejwt
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(
        seconds=config('JWT_ACCESS_TOKEN_LIFETIME', cast=int)
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        seconds=config('JWT_REFRESH_TOKEN_LIFETIME', cast=int)
    ),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}


# SECURITY HEADERS (HTTPS enforcement + cookies)
# Render (y cualquier proxy) termina TLS y reenvía al contenedor por HTTP
# interno. Sin esta cabecera Django cree que la petición es insegura:
# SECURE_SSL_REDIRECT redirige en bucle y las cookies Secure no se emiten.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# COOKIE DE REFRESH TOKEN (BUG-06) — ver apps/authentication/cookies.py
#
# El frontend productivo consume /api mediante el rewrite de Vercel, por lo que
# la cookie es first-party y SameSite=Lax funciona en local y producción. Cambiar
# a None requiere una revisión CSRF explícita y nunca debe combinarse con un
# comodín de orígenes credentialed.
AUTH_COOKIE_SAMESITE = config('AUTH_COOKIE_SAMESITE', default='Lax')
AUTH_COOKIE_SECURE = config('AUTH_COOKIE_SECURE', default=not DEBUG, cast=bool)

# El navegador solo adjunta cookies cross-origin si el servidor lo permite
# explícitamente y el cliente envía withCredentials.
CORS_ALLOW_CREDENTIALS = True


# DJANGO CHANNELS — tiempo real (Sprint 4)
USE_REDIS = config('USE_REDIS', default=False, cast=bool)

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': (
            'channels_redis.core.RedisChannelLayer'
            if USE_REDIS else
            'channels.layers.InMemoryChannelLayer'
        ),
        'CONFIG': (
            {'hosts': [config('REDIS_URL', default='redis://localhost:6379/0')]}
            if USE_REDIS else {}
        ),
    },
}


# EMAIL — notificaciones (Sprint 3 · S19–S22)
# Por defecto en DEBUG los correos se imprimen en la consola del runserver (no se
# envía nada real ni hace falta SMTP). Para ENVIAR correos reales aun con DEBUG=True,
# define EMAIL_BACKEND en el .env, p. ej. Gmail:
#   EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
#   EMAIL_HOST_USER=tucorreo@gmail.com
#   EMAIL_HOST_PASSWORD=<app password de Gmail, 16 caracteres>
_default_email_backend = (
    'django.core.mail.backends.console.EmailBackend' if DEBUG
    else 'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_BACKEND = config('EMAIL_BACKEND', default=_default_email_backend)
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
# SSL directo (puerto 465). Si EMAIL_USE_SSL=True, desactivar EMAIL_USE_TLS.
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
# Límite de espera del SMTP: si el servidor de correo no responde, el request
# no se congela — el registro continúa y el fallo de email solo queda en logs.
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=10, cast=int)

# ── Envío por API HTTPS (django-anymail) ───────────────────────────────────────
# Render bloquea/no rutea SMTP saliente (Errno 101), así que en producción el
# correo sale por la API HTTP de Brevo (puerto 443, siempre alcanzable).
# Activación: definir en el entorno
#   EMAIL_BACKEND=anymail.backends.brevo.EmailBackend
#   BREVO_API_KEY=xkeysib-...
#   DEFAULT_FROM_EMAIL=<remitente verificado en Brevo>
ANYMAIL = {
    "BREVO_API_KEY": config('BREVO_API_KEY', default=''),
}

DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='no-reply@sassblum.com')

# LN-3/LN-4 (paridad sistema legado): copia de cada email de notificación al equipo.
# Vacío = sin CC. Ej: EMAIL_CC=notificaciones@sassblum.com
EMAIL_CC = [e.strip() for e in config('EMAIL_CC', default='').split(',') if e.strip()]

# URL del frontend (para construir los enlaces de verificación / reseteo en los emails).
# El fallback depende de DEBUG a propósito: si la variable falta en el entorno de
# producción, los enlaces del correo NO deben apuntar a localhost (el usuario abriría
# un enlace muerto). Fuera de DEBUG el default es el dominio desplegado.
PRODUCTION_FRONTEND_URL = 'https://sassblum.vercel.app'
FRONTEND_URL = config(
    'FRONTEND_URL',
    default='http://localhost:5173' if DEBUG else PRODUCTION_FRONTEND_URL,
).rstrip('/')


# MISC
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# LOGGING — structured logging for production
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {'level': 'WARNING'},
        'apps': {'level': 'INFO'},
    },
}


# INTERNACIONALIZACIÓN
LANGUAGE_CODE = 'es-ec'
TIME_ZONE = 'America/Guayaquil'
USE_I18N = True
USE_TZ = True


# ARCHIVOS ESTÁTICOS
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# SUPABASE STORAGE — fotos de servicios + adjuntos de tickets
# Crea un bucket PÚBLICO en Supabase Storage (Storage → New bucket → "public").
# La service_role key es solo de servidor; NUNCA la expongas en el frontend.
# Si estas variables quedan vacías, StorageService usa una URL stub local (dev sin bucket).
SUPABASE_URL = config('SUPABASE_URL', default='')
SUPABASE_SERVICE_KEY = config('SUPABASE_SERVICE_KEY', default='')
SUPABASE_STORAGE_BUCKET = config('SUPABASE_STORAGE_BUCKET', default='SassBlumImagenes')
