"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.0.5.
https://docs.djangoproject.com/en/6.0/topics/settings/
"""

# IMPORTS
from pathlib import Path
from datetime import timedelta
from decouple import config
import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent


# SEGURIDAD
SECRET_KEY = config('DJANGO_SECRET_KEY')
DEBUG = config('DJANGO_DEBUG', cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')


# APLICACIONES
INSTALLED_APPS = [
    'daphne',
    # Django defaults
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'channels',
    # SassBlum apps
    'apps.authentication',
    'apps.catalog',
    'apps.gallery',
    'apps.tickets',
    'apps.notifications',
    'apps.reports',
    'apps.realtime',
]


# MIDDLEWARE
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',          # Debe ir primero
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# CORS
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in config(
        'CORS_ALLOWED_ORIGINS', default='http://localhost:5173'
    ).split(',')
]

# CORS preflight cache — reduce OPTIONS requests
CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours

# Permitir cualquier subdominio de vercel.app (deploys y previews)
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.vercel\.app$",
]

# Content-Security-Policy — OWASP A03:2021 defense-in-depth
SELF_SRC = "'self'"
CSP_DEFAULT_SRC = (SELF_SRC,)
CSP_SCRIPT_SRC = (SELF_SRC,)
CSP_STYLE_SRC = (SELF_SRC, "'unsafe-inline'")
CSP_IMG_SRC = (SELF_SRC, "data:", "https://images.unsplash.com")
CSP_FONT_SRC = (SELF_SRC, "https://fonts.gstatic.com")
CSP_CONNECT_SRC = (SELF_SRC,)


# URLS Y WSGI / ASGI
ROOT_URLCONF = 'config.urls'
WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'   # Requerido por Django Channels


# TEMPLATES
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# BASE DE DATOS — Supabase / PostgreSQL
DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL'),
        conn_max_age=config('CONN_MAX_AGE', default=0, cast=int),
    )
}


# MODELO DE USUARIO PERSONALIZADO
AUTH_USER_MODEL = 'authentication.User'


# VALIDACIÓN DE CONTRASEÑAS
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# DJANGO REST FRAMEWORK
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Rate limiting — OWASP A07:2021
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/minute',
        'user': '100/minute',
    },
    # Pagination — prevents huge responses
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}


# JWT — djangorestframework-simplejwt
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(
        seconds=config('JWT_ACCESS_TOKEN_LIFETIME', cast=int)
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        seconds=config('JWT_REFRESH_TOKEN_LIFETIME', cast=int)
    ),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}


# SECURITY HEADERS (HTTPS enforcement + cookies)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# DJANGO CHANNELS — tiempo real (Sprint 4)
USE_REDIS = config('USE_REDIS', default=False, cast=bool)

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': (
            'channels_redis.core.RedisChannelLayer'
            if USE_REDIS else
            'channels.layers.InMemoryChannelLayer'
        ),
        'CONFIG': (
            {'hosts': [config('REDIS_URL', default='redis://localhost:6379/0')]}
            if USE_REDIS else {}
        ),
    },
}


# EMAIL — notificaciones (Sprint 3 · S19–S22)
# Por defecto en DEBUG los correos se imprimen en la consola del runserver (no se
# envía nada real ni hace falta SMTP). Para ENVIAR correos reales aun con DEBUG=True,
# define EMAIL_BACKEND en el .env, p. ej. Gmail:
#   EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
#   EMAIL_HOST_USER=tucorreo@gmail.com
#   EMAIL_HOST_PASSWORD=<app password de Gmail, 16 caracteres>
_default_email_backend = (
    'django.core.mail.backends.console.EmailBackend' if DEBUG
    else 'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_BACKEND = config('EMAIL_BACKEND', default=_default_email_backend)
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)

DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='no-reply@sassblum.com')

# LN-3/LN-4 (paridad sistema legado): copia de cada email de notificación al equipo.
# Vacío = sin CC. Ej: EMAIL_CC=notificaciones@sassblum.com
EMAIL_CC = [e.strip() for e in config('EMAIL_CC', default='').split(',') if e.strip()]

# URL del frontend (para construir los enlaces de verificación / reseteo en los emails)
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:5173')


# MISC
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# LOGGING — structured logging for production
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {'level': 'WARNING'},
        'apps': {'level': 'INFO'},
    },
}


# INTERNACIONALIZACIÓN
LANGUAGE_CODE = 'es-ec'
TIME_ZONE = 'America/Guayaquil'
USE_I18N = True
USE_TZ = True


# ARCHIVOS ESTÁTICOS
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# SUPABASE STORAGE — fotos de servicios + adjuntos de tickets
# Crea un bucket PÚBLICO en Supabase Storage (Storage → New bucket → "public").
# La service_role key es solo de servidor; NUNCA la expongas en el frontend.
# Si estas variables quedan vacías, StorageService usa una URL stub local (dev sin bucket).
SUPABASE_URL = config('SUPABASE_URL', default='')
SUPABASE_SERVICE_KEY = config('SUPABASE_SERVICE_KEY', default='')
SUPABASE_STORAGE_BUCKET = config('SUPABASE_STORAGE_BUCKET', default='sassblum')
