# Generated by Django 6.0.5 on 2026-06-02 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_activo', models.BooleanField(default=True, verbose_name='email activo')),
                ('in_app_activo', models.BooleanField(default=True, verbose_name='in-app activo')),
                ('ws_activo', models.BooleanField(default=True, verbose_name='websocket activo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada en')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_notificacion', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'db_table': 'notifications_preference',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('creacion', 'Creación'), ('cambio_estado', 'Cambio de estado'), ('comentario', 'Comentario'), ('asignacion', 'Asignación'), ('reasignacion', 'Reasignación'), ('informacion', 'Información')], default='informacion', max_length=20, verbose_name='tipo')),
                ('titulo', models.CharField(max_length=160, verbose_name='título')),
                ('cuerpo', models.TextField(verbose_name='cuerpo')),
                ('leida', models.BooleanField(default=False, verbose_name='leída')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Datos del evento original (ticket_numero, estados, etc.).', verbose_name='payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada en')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(condition=models.Q(('leida', False)), fields=['usuario'], name='notif_unread_by_user_idx'), models.Index(fields=['usuario', 'created_at'], name='notificatio_usuario_7d52ec_idx')],
            },
        ),
    ]
