# Generated by Django 6.0.5 on 2026-06-02 15:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='bloqueado_hasta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='bloqueado hasta'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verificado',
            field=models.BooleanField(default=False, verbose_name='email verificado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('bloqueado', 'Bloqueado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='intentos_fallidos',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='intentos fallidos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Cliente'), ('worker', 'Trabajador'), ('admin', 'Administrador')], default='client', max_length=20, verbose_name='rol'),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token')),
                ('expira_en', models.DateTimeField(verbose_name='expira en')),
                ('usado', models.BooleanField(default=False, verbose_name='usado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'db_table': 'auth_password_reset_token',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='auth_passwo_token_ceb1cb_idx')],
            },
        ),
    ]
