# Generated by Django 6.0.5 on 2026-08-15 20:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='calificación')),
                ('comentario', models.CharField(max_length=500, verbose_name='comentario')),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=12, verbose_name='estado')),
                ('nota_moderacion', models.CharField(blank=True, default='', max_length=300, verbose_name='nota de moderación')),
                ('moderado_en', models.DateTimeField(blank=True, null=True, verbose_name='moderado en')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial', to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
                ('moderado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials_moderated', to=settings.AUTH_USER_MODEL, verbose_name='moderado por')),
            ],
            options={
                'db_table': 'testimonials_testimonial',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['estado', '-moderado_en'], name='testimonial_public_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('calificacion__gte', 1), ('calificacion__lte', 5)), name='testimonial_rating_between_1_and_5')],
            },
        ),
    ]
