# Generated by Django 6.0.5 on 2026-06-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='nombre')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('categoria', models.CharField(max_length=80, verbose_name='categoría')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
            ],
            options={
                'db_table': 'catalog_service',
                'ordering': ['categoria', 'nombre'],
                'indexes': [models.Index(fields=['activo', 'categoria'], name='catalog_ser_activo_0c09d4_idx')],
            },
        ),
    ]
