# Generated by Django 6.0.5 on 2026-06-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='imagen_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='URL de imagen'),
        ),
    ]
