# Generated by Django 6.0.5 on 2026-06-02 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Formato T-YYYY-NNNN. Generado por TicketService, nunca por el modelo.', max_length=20, unique=True, verbose_name='número de ticket')),
                ('asunto', models.CharField(max_length=80, verbose_name='asunto')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('EnProceso', 'En Proceso'), ('EnEspera', 'En Espera'), ('Resuelto', 'Resuelto'), ('Cerrado', 'Cerrado')], default='Nuevo', max_length=20, verbose_name='estado')),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Critica', 'Crítica')], default='Media', max_length=10, verbose_name='prioridad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL, verbose_name='trabajador asignado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_creados', to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='catalog.service', verbose_name='servicio')),
            ],
            options={
                'db_table': 'tickets_ticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255, verbose_name='nombre del archivo')),
                ('url', models.URLField(help_text='URL pública o firmada retornada por IStorageService.upload().', max_length=1000, verbose_name='URL de acceso')),
                ('tamaño_bytes', models.PositiveIntegerField(verbose_name='tamaño (bytes)')),
                ('mime_type', models.CharField(max_length=100, verbose_name='tipo MIME')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='subido en')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='tickets.ticket', verbose_name='ticket')),
            ],
            options={
                'db_table': 'tickets_attachment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('creacion', 'Creación'), ('cambio_estado', 'Cambio de estado'), ('comentario', 'Comentario'), ('asignacion', 'Asignación'), ('reasignacion', 'Reasignación')], max_length=20, verbose_name='tipo de evento')),
                ('estado_anterior', models.CharField(blank=True, default='', help_text='Vacío para eventos que no cambian estado (comentarios, asignaciones).', max_length=20, verbose_name='estado anterior')),
                ('estado_nuevo', models.CharField(blank=True, default='', max_length=20, verbose_name='estado nuevo')),
                ('comentario', models.TextField(help_text='Requerido para CAMBIO_ESTADO (BR-35). Opcional para otros tipos.', verbose_name='comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registrado en')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_events', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='tickets.ticket', verbose_name='ticket')),
            ],
            options={
                'db_table': 'tickets_ticket_event',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['cliente', 'estado'], name='tickets_tic_cliente_3bc696_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['asignado', 'estado'], name='tickets_tic_asignad_a52986_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['estado', 'prioridad'], name='tickets_tic_estado_03d285_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketevent',
            index=models.Index(fields=['ticket', 'created_at'], name='tickets_tic_ticket__fec572_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketevent',
            index=models.Index(fields=['ticket', 'tipo_evento'], name='tickets_tic_ticket__e6b82d_idx'),
        ),
    ]
