# Generated by Django 6.0.7 on 2026-08-23 00:16

from django.db import migrations, models


SYSTEM_EVENT_AUTHOR_NAME = "Sistema (migración histórica)"
BATCH_SIZE = 500


def backfill_event_author_names(apps, schema_editor):
    """Freeze the currently visible author without firing TicketEvent signals."""
    ticket_event = apps.get_model("tickets", "TicketEvent")
    database = schema_editor.connection.alias
    pending = []

    events = (
        ticket_event.objects.using(database)
        .select_related("autor")
        .order_by("pk")
        .iterator(chunk_size=BATCH_SIZE)
    )
    for event in events:
        if event.autor is None:
            event.autor_nombre = SYSTEM_EVENT_AUTHOR_NAME
        else:
            event.autor_nombre = (
                f"{event.autor.first_name} {event.autor.last_name}".strip()
                or event.autor.email
            )
        pending.append(event)
        if len(pending) == BATCH_SIZE:
            ticket_event.objects.using(database).bulk_update(
                pending,
                ["autor_nombre"],
                batch_size=BATCH_SIZE,
            )
            pending.clear()

    if pending:
        ticket_event.objects.using(database).bulk_update(
            pending,
            ["autor_nombre"],
            batch_size=BATCH_SIZE,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_contact_email_and_audit_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketevent',
            name='autor_nombre',
            field=models.CharField(
                blank=True,
                default='',
                editable=False,
                help_text=(
                    'Copia inmutable del nombre visible cuando se registró el evento.'
                ),
                max_length=301,
                verbose_name='nombre histórico del autor',
            ),
        ),
        migrations.RunPython(
            backfill_event_author_names,
            migrations.RunPython.noop,
        ),
    ]
